obj-$(CONFIG_SND_STM) += snd-stm.o
snd-stm-y := init.o common.o fsynth.o
snd-stm-y += conv.o conv_i2sspdif.o conv_int_dac.o
snd-stm-y += pcm_player.o pcm_reader.o spdif_player.o

obj-$(CONFIG_SND_STM_STX710X) += snd-stm-stx710x.o
snd-stm-stx710x-y := stx710x.o

obj-$(CONFIG_SND_STM_STX7105) += snd-stm-stx7105.o
snd-stm-stx7105-y := stx7105.o

obj-$(CONFIG_SND_STM_STX7111) += snd-stm-stx7111.o
snd-stm-stx7111-y := stx7111.o

obj-$(CONFIG_SND_STM_STX7141) += snd-stm-stx7141.o
snd-stm-stx7141-y := stx7141.o

obj-$(CONFIG_SND_STM_STX7200) += snd-stm-stx7200.o
snd-stm-stx7200-y := stx7200.o

obj-$(CONFIG_SND_STM_CONV_DUMMY) += snd-stm-conv-dummy.o
snd-stm-conv-dummy-y := conv_dummy.o

obj-$(CONFIG_SND_STM_CONV_GPIO) += snd-stm-conv-gpio.o
snd-stm-conv-gpio-y := conv_gpio.o

obj-$(CONFIG_SND_STM_CONV_EPLD) += snd-stm-conv-epld.o
snd-stm-conv-epld-y := conv_epld.o

obj-$(CONFIG_SND_STM_CONV_I2C) += snd-stm-conv-i2c.o
snd-stm-conv-i2c-y := conv_i2c.o
