#ifndef __SND_STM_7141_AUDCFG_H
#define __SND_STM_7141_AUDCFG_H



/*
 * 7141_AUDCFG_IO_CTRL
 */

#define offset__7141_AUDCFG_IO_CTRL(ip) 0x00
#define get__7141_AUDCFG_IO_CTRL(ip) readl(ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip))
#define set__7141_AUDCFG_IO_CTRL(ip, value) writel(value, ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip))

/* CLKREC_SEL */

#define shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip) 9
#define mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip) 0x3
#define get__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip) ((readl(ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip)) >> \
	shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip)) & \
	mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip, value) \
	writel((readl(ip->base + offset__7141_AUDCFG_IO_CTRL(ip)) & \
	~(mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip) << \
	shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip))) | (((value) & \
	mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip)) << \
	shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip)), ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip))

#define value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPLHDMI(ip) 0x0
#define mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPLHDMI(ip) \
	(value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPLHDMI(ip) << \
	shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPLHDMI(ip) \
	set__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPLHDMI(ip))

#define value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__SPDIFHDMI(ip) 0x1
#define mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL__SPDIFHDMI(ip) \
	(value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__SPDIFHDMI(ip) << \
	shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__CLKREC_SEL__SPDIFHDMI(ip) \
	set__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__SPDIFHDMI(ip))

#define value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL1(ip) 0x2
#define mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL1(ip) \
	(value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL1(ip) << \
	shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL1(ip) \
	set__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL1(ip))

#define value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL0(ip) 0x3
#define mask__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL0(ip) \
	(value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL0(ip) << \
	shift__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL0(ip) \
	set__7141_AUDCFG_IO_CTRL__CLKREC_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__CLKREC_SEL__PCMPL0(ip))

/* PCMR1_SCLK_INV_SEL */

#define shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip) 12
#define mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip) 0x1
#define get__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip) \
	((readl(ip->base + offset__7141_AUDCFG_IO_CTRL(ip)) >> \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip)) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip, value) \
	writel((readl(ip->base + offset__7141_AUDCFG_IO_CTRL(ip)) & \
	~(mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip))) | (((value) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip)) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip)), ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip))

#define \
	value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__NO_INVERSION(ip) 0x0
#define \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__NO_INVERSION(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__NO_INVERSION(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__NO_INVERSION(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__NO_INVERSION(ip))

#define value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__INVERSION(ip) \
	0x1
#define mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__INVERSION(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__INVERSION(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__INVERSION(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_INV_SEL__INVERSION(ip))

/* PCMR1_LRCLK_RET_SEL */

#define shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip) 13
#define mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip) 0x1
#define get__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip) \
	((readl(ip->base + offset__7141_AUDCFG_IO_CTRL(ip)) >> \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip)) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip, value) \
	writel((readl(ip->base + offset__7141_AUDCFG_IO_CTRL(ip)) & \
	~(mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip))) | (((value) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip)) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip)), ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip))

#define \
	value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__NO_RETIMIMG(ip) 0x0
#define \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__NO_RETIMIMG(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__NO_RETIMIMG(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__NO_RETIMIMG(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__NO_RETIMIMG(ip))

#define \
	value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__RETIME_BY_1_CYCLE(ip) \
	0x1
#define \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__RETIME_BY_1_CYCLE(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__RETIME_BY_1_CYCLE(ip) \
	<< shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip))
#define \
	set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__RETIME_BY_1_CYCLE(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_RET_SEL__RETIME_BY_1_CYCLE(ip))

/* PCMR1_SCLK_SEL */

#define shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip) 14
#define mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip) 0x1
#define get__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip) ((readl(ip->base \
	+ offset__7141_AUDCFG_IO_CTRL(ip)) >> \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip)) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip, value) \
	writel((readl(ip->base + offset__7141_AUDCFG_IO_CTRL(ip)) & \
	~(mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip))) | (((value) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip)) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip)), ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip))

#define value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PAD(ip) 0x0
#define mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PAD(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PAD(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PAD(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PAD(ip))

#define \
	value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PCM_PLAYER_0(ip) 0x1
#define \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PCM_PLAYER_0(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PCM_PLAYER_0(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip))
#define \
	set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PCM_PLAYER_0(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_SCLK_SEL__FROM_PCM_PLAYER_0(ip))

/* PCMR1_LRCLK_SEL */

#define shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip) 15
#define mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip) 0x1
#define get__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip) ((readl(ip->base \
	+ offset__7141_AUDCFG_IO_CTRL(ip)) >> \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip)) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip, value) \
	writel((readl(ip->base + offset__7141_AUDCFG_IO_CTRL(ip)) & \
	~(mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip))) | (((value) & \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip)) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip)), ip->base + \
	offset__7141_AUDCFG_IO_CTRL(ip))

#define value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PAD(ip) 0x0
#define mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PAD(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PAD(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip))
#define set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PAD(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PAD(ip))

#define \
	value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PCM_PLAYER_0(ip) 0x1
#define \
	mask__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PCM_PLAYER_0(ip) \
	(value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PCM_PLAYER_0(ip) << \
	shift__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip))
#define \
	set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PCM_PLAYER_0(ip) \
	set__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL(ip, \
	value__7141_AUDCFG_IO_CTRL__PCMR1_LRCLK_SEL__FROM_PCM_PLAYER_0(ip))



#endif
